Zycient/ZDAWebsite

.gitignore
--------
- Adds the first gitignore to the repo.
=> feat: add v1 of gitignore

package-lock.json, package.json, src/App.tsx, src/components/ThemeToggle.tsx, src/main.tsx, src/states/ThemeAtom.ts
--------
- Add Joy UI and test button
- Add basic dark mode Switch from Joy UI
- Add basic Recoil state management for the theme
=> Feat: Init Joy UI and add base Recoil State Management

src/App.tsx, src/Helpers.ts, src/components/HamburgerMenu.tsx, src/components/ThemeToggle.tsx, src/components/sections/BodySection.tsx, src/components/sections/FooterSection.tsx, src/components/sections/TopBanner.tsx, src/components/sections/TopInfoSection.tsx, src/index.css, src/states/CommSlotsAtom.ts, src/states/PageAtom.ts
- Init the section stubs
- Added global helpers file
- Added comm status to atom
- Tweaked CSS background color for Dark Mode
=> Feat: Init Section Stubs

src/components/ThemeToggle.tsx
--------
- Working Dark Mode Toggle with OS preference detection and localStorage for saving user pref
=> Feat: working Theme Toggle with OS detection and local storage

src/components/sections/FooterSection.tsx, src/components/sections/FooterSectionSx.ts
--------
- Much better styling for footer icon buttons using separate Sx for Dark Mode
=> Fix: better icon and iconbutton colors for footer with Sx

src/components/HamburgerMenu.tsx, src/components/sections/TopBanner.css, src/components/sections/TopBanner.tsx, src/components/sections/TopBannerSx.ts
--------
- Top Banner v1: logo, title, dynamic page text, underlines buttons when matched to page
- Better styles and alignment (just for desktop for now)
=> Feat: Top Banner v1

src/App.css, src/App.tsx, src/AppSx.ts, src/components/HamburgerMenu.tsx, src/components/HamburgerMenuSx.ts, src/components/ThemeToggle.tsx, src/components/sections/BodySection.tsx, src/components/sections/BodySectionSx.ts, src/components/sections/TopBanner.tsx, src/components/sections/TopBannerSx.ts, src/components/sections/TopInfoSection.css, src/components/sections/TopInfoSection.tsx, src/components/sections/TopInfoSectionSx.ts
--------
- Custom Cards and Light/Dark Styles for Top Info: 
- Home
- Portfolio
- Commissions
- Media Queries for Top Banner (Phone/Tablet, Desktop)
- Redo of Hamburger Menu styles
- Removed fluff at bottom of App.tsx
- Added Transition All for Theme Toggling
=> Feat: Top Info Section v1 and Top Banner Fixes

src/components/sections/BodySectionSx.ts, src/components/sections/FooterSection.css, src/components/sections/FooterSection.tsx, src/components/sections/FooterSectionSx.ts
------
- Footer elements and sx
- Converted from IconButton to Button with startDecorator
- Updated Privacy Policy link to new tinyurl
- Fixed Commissions - Abstractify - Title and Description legibility for mobile
=> Feat: Footer Section v1

.eslintrc.cjs, .gitignore, package-lock.json, package.json, src/App.css, src/App.tsx, src/components/sections/TopInfoSection.css, src/components/sections/TopInfoSection.tsx, src/states/CommSlotsAtom.ts
------
- Use REST API (fetch) to hit Vercel KV for Commission Slots (Active, Waitlist) and compute Status
- Use Spinner and Modal Backdrop to defeat race condition when grabbing data
=> Feat: Vercel KV API for Commission Slots and Status

src/components/HamburgerMenu.tsx, src/components/ThemeToggle.tsx, src/components/sections/BodySection.tsx, src/components/sections/BodySectionSx.ts, src/components/sections/FooterSection.tsx, src/components/sections/TopBanner.tsx, src/components/sections/TopBannerSx.ts, src/components/sections/TopInfoSection.tsx
------
- Better text color contrasts
- ARIA labels, descriptions where needed
- HTML titles where needed
=> Tweaks and Fixes for Accessibility

src/routes/ErrorPage.tsx
------
- Fixed the capitalization on the paths passed to switchPage() from ErrorPage
=> Fix: Correct capitalization on paths from ErrorPage

package-lock.json, package.json, src/components/sections/BodySection.tsx, src/components/sections/TopBanner.tsx, src/components/sections/TopInfoSection.tsx
------
- Use the commStatus atom, convert to bool, and pass to `disabled` prop on comm form buttons
=> Feat: Disable Commission Form Buttons When Closed Status

package-lock.json, package.json, src/components/sections/BodySection.css, src/components/sections/BodySectionSx.ts
------
- Added media queries for logo size and margin on phone and tablet
- Added media query for hidden text to go to center for phone and tablet
=> Feat: Logo Page Media Queries for Mobile

src/main.tsx
------
Per instructions [here](https://fontsource.org/docs/getting-started/install), import the Fontsource fonts in main entry point.
=> Fix: import fontsource fonts in main

public/loading.css, src/components/HamburgerMenu.tsx, src/components/HamburgerMenuSx.ts, src/components/sections/BodySectionSx.ts, src/components/sections/FooterSectionSx.ts, src/components/sections/TopInfoSection.css, src/components/sections/TopInfoSectionSx.ts, src/index.css, src/main.tsx
------
- Used manual imports to get all font weights, for both normal and italic styles
- Explicitly used 600 font weight instead of just "bold" in Hamburger
- Added `Inter` as a fallback font before using `system`
=> Fix: Manual Font Imports and Inter Fallback

package-lock.json, package.json, public/zerodayanubis_textlogo_dark.svg, public/zerodayanubis_textlogo_light.svg, src/components/sections/TopInfoSection.css, src/components/sections/TopInfoSection.tsx, src/components/sections/TopInfoSectionSx.ts
------
- New "ZeroDayAnubis" full long text logo for TopInfoSection's Left Title
=> Feat: New ZeroDayAnubis Long Text Logo

package-lock.json, package.json, src/main.tsx
------
Fix the display of the footer and Top Info SVG logos by importing `Urbanist` font from fontsource install
=> Fix: do main import of Urbanist for logos

index.html, package-lock.json, package.json
------
Change max-snippet to 101 so that Google Search does cutoff on 2nd sentence instead of midway through 3rd.
=> Fix: change max snippet to 101

index.html, package-lock.json
- Updates theme-color in index.html to zdaRedpink-600 value
- Updates caniuse-lite in package-lock.json
=> Tweak: Update Index Theme to ZDA Redpink 600

package-lock.json, package.json, public/robots.txt, public/sitemap.xml
Added basic sitemap in XML format.
=> Feat: Add Sitemap

package-lock.json, package.json, src/helpers.ts, src/sections/Footer/Footer.tsx
Resolves #64 by updating references to old GMail address to new Proton Mail based address.
=> Tweak: Update Email Address To Use New Proton Mail

package-lock.json, package.json, src/links.ts
Replaces static comm form/info, privacy policy, and print shop links with the dynamic versions on short.io.
=> Tweak: Use Dynamic Short IO Links

package-lock.json, package.json, src/components/ThemeMenu.tsx, src/states/themeAtom.ts
Resolves #76 
Changes font to semibold (essentially highlighting) for currently active theme/colorScheme in the ThemeMenu.
Also refactors the DropdownMenu Items to dynamically map the JSX, for themes and then colorSchemes, to better support additions in the future.
=> Feat: Highlight Active Theme and ColorScheme

package-lock.json, package.json, src/App.tsx
Resolves #83 
- Enables Speed Insights feature from Vercel
- Updates Web Analytics Vercel package from 1.2.2 to 1.4.1
=> Feature: Add Speed Insights from Vercel

package-lock.json, package.json, src/App.tsx
Resolves #87 and increments version to v2.8.1 (I forgot to increment with last merge to master).
=> Chore: Remove Vercel Speed Insights

README.md, index.html, package-lock.json, package.json
Adds verification anchor for the mastoart.social Mastodon instance.
Also adds the Writing Page section to the README.
=> Feature: Add verification for mastoart social

package-lock.json, package.json, src/Writings.ts, src/pages/AboutPage.tsx
- Added "How Lovely" poem
- Did slight tweaks to allergies rant title
- Renamed myself to "Zero" in About
=> Feat: Add How Lovely Poem
